/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationsIndexRouteImport } from './routes/stations/index'
import { Route as StationsStationCodeRouteImport } from './routes/stations/$stationCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIndexRoute = StationsIndexRouteImport.update({
  id: '/stations/',
  path: '/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationCodeRoute = StationsStationCodeRouteImport.update({
  id: '/stations/$stationCode',
  path: '/stations/$stationCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stations/$stationCode': typeof StationsStationCodeRoute
  '/stations/': typeof StationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stations/$stationCode': typeof StationsStationCodeRoute
  '/stations': typeof StationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stations/$stationCode': typeof StationsStationCodeRoute
  '/stations/': typeof StationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stations/$stationCode' | '/stations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stations/$stationCode' | '/stations'
  id: '__root__' | '/' | '/stations/$stationCode' | '/stations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StationsStationCodeRoute: typeof StationsStationCodeRoute
  StationsIndexRoute: typeof StationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/': {
      id: '/stations/'
      path: '/stations'
      fullPath: '/stations/'
      preLoaderRoute: typeof StationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationCode': {
      id: '/stations/$stationCode'
      path: '/stations/$stationCode'
      fullPath: '/stations/$stationCode'
      preLoaderRoute: typeof StationsStationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StationsStationCodeRoute: StationsStationCodeRoute,
  StationsIndexRoute: StationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
